# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: Build and run go code
    cmds:
      - task: run

  run: go run .

  build: go build .
